#!/usr/bin/env bash
# Generate site/index.html by concatenating:
#   site/templates/header.html  (hero, sections, demo, why, what, how, showcase intro)
#   <auto-generated cards from corpus/manifest.json + data/<id>.json>
#   site/templates/footer.html  (install, family, footer)
#
# Placeholders __VERSION__, __TEST_COUNT__, __GENERATED__ are substituted
# in the final output.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MANIFEST="$ROOT/corpus/manifest.json"
DATA="$ROOT/data"
SOURCE="$ROOT/corpus/files"
SITE="$ROOT/site"
TPL="$SITE/templates"
IMAGES="$SITE/images"

mkdir -p "$IMAGES"

VERSION=$(auge --version 2>/dev/null | awk '{print $2}' | sed 's/^v//' || echo "—")
GENERATED=$(date "+%Y-%m-%d")

# Pull test count from auge repo if present
TEST_COUNT="187"
AUGE_REPO=$(cd "$ROOT/../auge" 2>/dev/null && pwd || echo "")
if [ -n "$AUGE_REPO" ] && [ -d "$AUGE_REPO" ]; then
    if [ -x "$AUGE_REPO/.build/debug/auge-tests" ]; then
        actual=$("$AUGE_REPO/.build/debug/auge-tests" 2>/dev/null | grep -oE '[0-9]+ tests passed' | grep -oE '[0-9]+' | head -1 || echo "")
        if [ -n "$actual" ]; then TEST_COUNT="$actual"; fi
    fi
fi

echo "auge-web: building site/index.html (auge v$VERSION, $TEST_COUNT tests)..."

html_escape() { python3 -c 'import sys, html; print(html.escape(sys.stdin.read()), end="")'; }

pretty_json_file() {
  if [ -f "$1" ] && [ -s "$1" ]; then
    cat "$1" | python3 -c 'import sys,json; sys.stdout.write(json.dumps(json.load(sys.stdin), indent=2, ensure_ascii=False))'
  fi
}

render_cmdline() {
  local args_json="$1"
  local filename="$2"
  local out='<span class="prompt">$</span> auge'
  while IFS= read -r arg; do
    if [[ "$arg" == --* ]]; then
      out+=" <span class=\"flag\">$(echo "$arg" | html_escape)</span>"
    else
      out+=" <span class=\"arg\">$(echo "$arg" | html_escape)</span>"
    fi
  done < <(echo "$args_json" | jq -r '.[]')
  out+=" $(echo "$filename" | html_escape)"
  echo "$out"
}

render_ocr_section() {
  local json_file="$1"
  local lines_json
  lines_json=$(jq -c '.results.ocr.lines // .results.lines // []' "$json_file" 2>/dev/null || echo '[]')
  local count text chars
  count=$(echo "$lines_json" | jq 'length')
  text=$(echo "$lines_json" | jq -r 'join("\n")')
  chars=$(printf '%s' "$text" | wc -c | tr -d ' ')

  if [ "$count" -eq 0 ] || [ -z "$text" ]; then
    cat <<EOF
<div class="section-block">
  <div class="section-head">
    <span class="icon ocr">A</span>
    <span class="label">OCR</span>
    <span class="stats">no text</span>
  </div>
  <div class="empty-msg">No text detected in this image.</div>
</div>
EOF
    return
  fi

  cat <<EOF
<div class="section-block">
  <div class="section-head">
    <span class="icon ocr">A</span>
    <span class="label">OCR</span>
    <span class="stats">${count} line$([ "$count" -ne 1 ] && echo s || true) &middot; ${chars} chars</span>
  </div>
  <pre class="ocr-text">$(printf '%s' "$text" | html_escape)</pre>
</div>
EOF
}

render_classify_section() {
  local json_file="$1"
  local items_json
  items_json=$(jq -c '.results.classify.classifications // .results.classifications // []' "$json_file" 2>/dev/null || echo '[]')
  local count
  count=$(echo "$items_json" | jq 'length')

  if [ "$count" -eq 0 ]; then
    cat <<EOF
<div class="section-block">
  <div class="section-head">
    <span class="icon classify">#</span>
    <span class="label">Classify</span>
    <span class="stats">no labels</span>
  </div>
  <div class="empty-msg">No classification labels above the confidence threshold.</div>
</div>
EOF
    return
  fi

  cat <<EOF
<div class="section-block">
  <div class="section-head">
    <span class="icon classify">#</span>
    <span class="label">Classify</span>
    <span class="stats">${count} label$([ "$count" -ne 1 ] && echo s || true)</span>
  </div>
  <div class="classify-list">
EOF

  echo "$items_json" | jq -c '.[]' | while IFS= read -r row; do
    local label conf pct label_e
    label=$(echo "$row" | jq -r '.label')
    conf=$(echo "$row" | jq -r '.confidence')
    pct=$(awk "BEGIN { printf \"%.0f\", $conf * 100 }")
    label_e=$(echo "$label" | html_escape)
    cat <<EOF
    <div class="classify-row">
      <div class="classify-bar"><div class="fill" style="width:${pct}%"></div><div class="text">${label_e}</div></div>
      <div class="classify-pct">${pct}%</div>
    </div>
EOF
  done

  cat <<EOF
  </div>
</div>
EOF
}

render_barcodes_section() {
  local json_file="$1"
  local items_json
  items_json=$(jq -c '.results.barcodes.barcodes // .results.barcodes // []' "$json_file" 2>/dev/null || echo '[]')
  local count
  count=$(echo "$items_json" | jq 'length')

  if [ "$count" -eq 0 ]; then
    cat <<EOF
<div class="section-block">
  <div class="section-head">
    <span class="icon barcodes">▦</span>
    <span class="label">Barcodes</span>
    <span class="stats">none</span>
  </div>
  <div class="empty-msg">No barcodes or QR codes detected.</div>
</div>
EOF
    return
  fi

  cat <<EOF
<div class="section-block">
  <div class="section-head">
    <span class="icon barcodes">▦</span>
    <span class="label">Barcodes</span>
    <span class="stats">${count} found</span>
  </div>
  <div class="barcode-list">
EOF

  echo "$items_json" | jq -c '.[]' | while IFS= read -r row; do
    local sym payload sym_e payload_html
    sym=$(echo "$row" | jq -r '.symbology // "?"')
    payload=$(echo "$row" | jq -r '.payload // ""')
    sym_e=$(echo "$sym" | html_escape)
    if [[ "$payload" =~ ^https?:// ]]; then
      payload_html="<a href=\"$(echo "$payload" | html_escape)\" target=\"_blank\" rel=\"noopener\">$(echo "$payload" | html_escape)</a>"
    else
      payload_html=$(echo "$payload" | html_escape)
    fi
    cat <<EOF
    <div class="barcode-row">
      <span class="symbology">${sym_e}</span>
      <span class="payload">${payload_html}</span>
    </div>
EOF
  done

  cat <<EOF
  </div>
</div>
EOF
}

render_faces_section() {
  local json_file="$1"
  local items_json
  items_json=$(jq -c '.results.faces.faces // .results.faces // []' "$json_file" 2>/dev/null || echo '[]')
  local count
  count=$(echo "$items_json" | jq 'length')

  if [ "$count" -eq 0 ]; then
    cat <<EOF
<div class="section-block">
  <div class="section-head">
    <span class="icon faces">☻</span>
    <span class="label">Faces</span>
    <span class="stats">0 detected</span>
  </div>
  <div class="empty-msg">No faces detected.</div>
</div>
EOF
    return
  fi

  cat <<EOF
<div class="section-block">
  <div class="section-head">
    <span class="icon faces">☻</span>
    <span class="label">Faces</span>
    <span class="stats">${count} detected</span>
  </div>
  <div class="faces-summary">
    <span class="count">${count}</span> face$([ "$count" -ne 1 ] && echo s || true) located. Bounding boxes overlaid on the image above.
  </div>
  <div class="faces-list">
EOF

  local i=0
  echo "$items_json" | jq -c '.[]' | while IFS= read -r row; do
    i=$((i+1))
    local x y w h
    x=$(echo "$row" | jq -r '.x'); y=$(echo "$row" | jq -r '.y')
    w=$(echo "$row" | jq -r '.width'); h=$(echo "$row" | jq -r '.height')
    printf '    <div>face %s: x=%.3f y=%.3f w=%.3f h=%.3f</div>\n' "$i" "$x" "$y" "$w" "$h"
  done

  cat <<EOF
  </div>
</div>
EOF
}

render_face_overlay() {
  local json_file="$1"
  local items_json
  items_json=$(jq -c '.results.faces.faces // .results.faces // []' "$json_file" 2>/dev/null || echo '[]')
  local count
  count=$(echo "$items_json" | jq 'length')
  if [ "$count" -eq 0 ]; then return; fi
  echo '<div class="face-overlay">'
  local i=0
  echo "$items_json" | jq -c '.[]' | while IFS= read -r row; do
    i=$((i+1))
    local x y w h left top width height
    x=$(echo "$row" | jq -r '.x'); y=$(echo "$row" | jq -r '.y')
    w=$(echo "$row" | jq -r '.width'); h=$(echo "$row" | jq -r '.height')
    left=$(awk "BEGIN { printf \"%.2f\", $x * 100 }")
    top=$(awk "BEGIN { printf \"%.2f\", (1 - $y - $h) * 100 }")
    width=$(awk "BEGIN { printf \"%.2f\", $w * 100 }")
    height=$(awk "BEGIN { printf \"%.2f\", $h * 100 }")
    printf '<div class="face-box" style="left:%s%%;top:%s%%;width:%s%%;height:%s%%"><div class="label">face %d</div></div>\n' \
      "$left" "$top" "$width" "$height" "$i"
  done
  echo '</div>'
}

build_card() {
  local idx="$1"
  local id title year category license source_url filename blurb args_json
  id=$(jq -r ".items[$idx].id" "$MANIFEST")
  title=$(jq -r ".items[$idx].title" "$MANIFEST")
  year=$(jq -r ".items[$idx].year" "$MANIFEST")
  category=$(jq -r ".items[$idx].category" "$MANIFEST")
  license=$(jq -r ".items[$idx].license" "$MANIFEST")
  source_url=$(jq -r ".items[$idx].source" "$MANIFEST")
  filename=$(jq -r ".items[$idx].filename" "$MANIFEST")
  blurb=$(jq -r ".items[$idx].blurb" "$MANIFEST")
  args_json=$(jq -c ".items[$idx].auge_args" "$MANIFEST")

  local src_image="$SOURCE/$filename"
  if [ ! -f "$src_image" ]; then return; fi

  local display_filename="$filename"
  if [[ "$filename" == *.pdf ]] || [[ "$filename" == *.PDF ]]; then
    local png_thumb="${filename%.*}.png"
    local png_path="$IMAGES/$png_thumb"
    if [ ! -f "$png_path" ]; then
      sips -s format png "$src_image" --out "$png_path" >/dev/null 2>&1 || cp "$src_image" "$png_path"
      sips -Z 900 "$png_path" --out "$png_path" >/dev/null 2>&1 || true
    fi
    display_filename="$png_thumb"
  else
    sips -Z 900 "$src_image" --out "$IMAGES/$filename" >/dev/null 2>&1 || cp "$src_image" "$IMAGES/$filename"
  fi

  local json_file="$DATA/$id.json"
  local cmdline pretty title_e blurb_e license_e source_e
  cmdline=$(render_cmdline "$args_json" "$filename")
  pretty=$(pretty_json_file "$json_file" | html_escape)
  title_e=$(echo "$title" | html_escape)
  blurb_e=$(echo "$blurb" | html_escape)
  license_e=$(echo "$license" | html_escape)
  source_e=$(echo "$source_url" | html_escape)

  cat <<EOF
<article class="card" id="$id">
  <div class="card-image">
    <div class="card-image-frame">
      <img src="images/$(echo "$display_filename" | html_escape)" alt="$title_e" loading="lazy">
$(render_face_overlay "$json_file")
    </div>
  </div>
  <div class="card-body">
    <div class="card-meta">
      <span class="badge $category">$category</span>
      <span>$year</span>
      <span>$license_e</span>
    </div>
    <h3>$title_e</h3>
    <p class="blurb">$blurb_e</p>
    <code class="cmd-line">$cmdline</code>
$(render_ocr_section "$json_file")
$(render_classify_section "$json_file")
$(render_barcodes_section "$json_file")
$(render_faces_section "$json_file")
    <div class="section-block">
      <div class="section-head">
        <span class="icon json">{}</span>
        <span class="label">Raw JSON</span>
        <span class="stats">on-device output</span>
      </div>
      <pre class="json-block">$pretty</pre>
    </div>
    <a class="source-link" href="$source_e" target="_blank" rel="noopener">Wikimedia source</a>
  </div>
</article>
EOF
}

# ---- Compose ----
TMP_BODY=$(mktemp)
trap 'rm -f "$TMP_BODY"' EXIT

count=$(jq '.items | length' "$MANIFEST")
for i in $(seq 0 $((count - 1))); do
    id=$(jq -r ".items[$i].id" "$MANIFEST")
    printf "  %-40s built\n" "$id"
    build_card "$i" >> "$TMP_BODY"
done

# Concatenate header + cards + footer, then substitute placeholders
{
  cat "$TPL/header.html"
  cat "$TMP_BODY"
  cat "$TPL/footer.html"
} | sed \
    -e "s|__VERSION__|$VERSION|g" \
    -e "s|__TEST_COUNT__|$TEST_COUNT|g" \
    -e "s|__GENERATED__|$GENERATED|g" \
  > "$SITE/index.html"

echo ""
echo "auge-web: site built at $SITE/index.html"
ls -lh "$SITE/index.html"
